Романенков Алексей Дмитриевич, Б05-231, 1 курс, контест 2, id - 85287250. Task A
leshicorn/MIPT-ALGO-2-TERM pull request #13
Opened 2023-04-07 00:42 UTC by leshicorn

2023-04-09 23:35 UTC, DmitrySteblovskiy requested changes

2023-04-09 23:35 UTC, DmitrySteblovskiy commented on Algo/contest2/contest2taskA/A.c
> +
У тебя в ПР к этой задаче висит 27 файлов, это ультра неудобно, не делай так, пожалуйста)

2023-04-09 23:35 UTC, DmitrySteblovskiy commented on Algo/contest2/contest2taskA/A.c
> +int max(int a, int b) {
Ох, больно смотреть на язык без Template :(
Будет желание, можешь на досуге прочитать, но переделывать на темплейты такие истории не обязательно
https://habr.com/ru/articles/154811/

2023-04-09 23:35 UTC, DmitrySteblovskiy commented on Algo/contest2/contest2taskA/A.c
> +int max(int a, int b) {
И не забываем про конст)

2023-04-09 23:35 UTC, DmitrySteblovskiy commented on Algo/contest2/contest2taskA/A.c
> +    int height;
Высота может быть отрицательной?

2023-04-09 23:35 UTC, DmitrySteblovskiy commented on Algo/contest2/contest2taskA/A.c
> +    node* y = x -> right;
По сути копипаст кода с предыдущей функцией, желательно избавиться
Например, создаешь функцию rotate (side: left or right)
И в RotateRight, RotateLeft вызываешь просто
Кстати, вас заставляют таким некрасивым кодстайлом для функций/методов пользоваться? По GoogleCodestyle так нельзя

2023-04-09 23:35 UTC, DmitrySteblovskiy commented on Algo/contest2/contest2taskA/A.c
> +    if (bf < -1 && val < root -> right -> key) {
Эх, снова хочеца меньше ифов, го вспомогательную функцию для избавления от копипаст

2023-04-09 23:35 UTC, DmitrySteblovskiy commented on Algo/contest2/contest2taskA/A.c
> +node * insert(node * root, int val) {
const int val

2023-04-09 23:35 UTC, DmitrySteblovskiy commented on Algo/contest2/contest2taskA/A.c
> +        int n, x = 0, result = 0;
Столько кода в Мейне быть не должно

2023-04-09 23:35 UTC, DmitrySteblovskiy commented on Algo/contest2/contest2taskA/A.c
> +        char op, prev_op = '+';
В 1м контесте мы банили проверки по одному символу 
Сейчас тоже) Такой способ не подходит для рабочего/учебного кода

2023-04-12 16:27 UTC, leshicorn commented on Algo/contest2/contest2taskA/A.c
> +        char op, prev_op = '+';
в ближайшее время все исправлю

2023-04-17 11:18 UTC, leshicorn commented on Algo/contest2/contest2taskA/A.c
> +    node* y = x -> right;
по поводу кодстайла наверное мой косяк, но я опирался на то, что на семах показывали, до конца не уверен, но скорее всего сделал так, как объяснили

2023-04-17 18:01 UTC, DmitrySteblovskiy commented on Algo/contest2/contest2taskA/A.c
> +    node* y = x -> right;
Уточнил у Влада: он не требует от вас гугловского кодстайла из-за деда. Так что, по сути, пиши как хочешь.
По Google Codestyle функции называются MakeSort.
https://google.github.io/styleguide/cppguide.html

2023-04-17 18:53 UTC, leshicorn commented on Algo/contest2/contest2taskA/A.c
> +    node* y = x -> right;
Понял, спасибо!

2023-04-19 10:29 UTC, leshicorn commented
Вроде все пофиксил

2023-04-19 15:49 UTC, DmitrySteblovskiy approved these changes
Обработку ввода можно выносить в отдельную функцию, но это мелочи. А вот что важно: я только сейчас заметил утечку памяти :(
ПР зачту, но утечку необходимо исправить и впредь не допускать. Для Си это важно.
А в остальном все хорошо.

2023-04-19 15:49 UTC, DmitrySteblovskiy commented
> Вроде все пофиксил

Да, но

2023-04-19 15:49 UTC, closed without merging